---
- name: Add host from loop
  set_fact:
    gaia: "{{ gaia | combine( {'host': gaia_host ~ '.' ~ gaia.domain} ) }}"
  when: gaia_host is defined and gaia.domain is defined

- name: Get Monitoring Info
  gaia2elastic:
    #CheckPoint Device
    gaia: "{{ gaia }}"
    datastore: "{{ datastore }}"
  register: modout
  ignore_errors: True
  no_log: False
  async: 600
  poll: 0

- name: Debug Info
  debug:
    var: modout
