---
- name: Get Monitoring Info
  gaia2elastic:
    #CheckPoint Device
    gaia: "{{ gaia }}"
    datastore: "{{ data_store }}"
  register: modout
  ignore_errors: True
  no_log: False
  async: 600
  poll: 0

- name: Debug Info
  debug:
    var: modout
